### PR TITLE
PhaKinPro Model incorporation into Ersilia

### PR DESCRIPTION
**Pull request by sucksido**
PhaKinPro Model incorporation into Ersilia

### CODE REVIEW

**Comment by sucksido** [comment]
OUTPUT:

[['SMILES', 'Hepatic Stability', 'Microsomal Half-life Sub-cellular', 'Microsomal Half-life Tissue', 'Renal Clearance', 'BBB Permeability', 'CNS Activity', 'CACO2', 'Plasma Protein Binding', 'Plasma Half-life', 'Microsomal Intrinsic Clearance', 'Oral Bioavailability'], ['COc1c(/C=N/NC(N)=S)c(CC(C)Cl)c(OC)c2c1OCO2', 0.6733, 0.71, 0.56, None, 0.632, 0.8320000000000001, 0.6679999999999999, 0.596, 0.637, 0.54, 0.5413], ['O=[N+]([O-])c1ccc(N/N=C/c2ccc([N+](=O)[O-])s2)cc1', 0.6347, 0.74, 0.52, None, 0.72, 0.828, 0.604, 0.524, 0.5820000000000001, 0.66, 0.58], ['CCCCOc1ccc(N2CC(C(=O)NCCc3ccc(OC)c(OC)c3)CC2=O)cc1', None, 0.53, 0.53, None, 0.604, 0.88, 0.584, 0.516, 0.624, 0.564, 0.54], ['O=C(Nc1cc(Cl)ccc1O)c1ccco1', 0.5533, 0.7, 0.8, None, 0.54, 0.892, 0.688, 0.7559999999999999, None, 0.708, 0.536]]

**Comment by GemmaTuron** [comment]
Hi @sucksido 

If you see above the automated tests are failing. In this case, it seems to be an issue with the metadata file - there is useful feedback on the Action, so have a look and correct it.

**Comment by GemmaTuron** [comment]
Hi @sucksido 
A few suggestions:
- The model is not a generative model (it does not do any new generation, it predicts properties so either a classifier or a regressor, depending on the output)
- The output is in Float format if I recall correctly from your example?
Also you can eliminate the mock.txt file and if there is no git lfs objects to be tracked, the gitattributes as well

**Comment by GemmaTuron** [comment]
Hi @sucksido 

The workflow files should not be modified in principle, why did you need to modify them?

**Comment by sucksido** [comment]
Hi @GemmaTuron i was installing missing dependancies, I have reverted the changes

**Comment by GemmaTuron** [comment]
Hi @sucksido 

Please look at the failed action and install the missing dependencies. A few points:
- Please update python so we are using at least 310
- Always pin the version of the packages used (copy what you had in your local set up)
- Please make sure to write the proper command to install the packages - the rdkit is an example

All of this is in the Dockerfile

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron and @sucksido - any action needed from my end?

**Comment by sucksido** [comment]
Thanks @GemmaTuron and @miquelduranfrigola , will be making these changes and deploying again

**Comment by sucksido** [comment]
Still getting errors, busy debugging

**Comment by sucksido** [comment]
Current error, not ecaxtly sure where or how to fix this one @GemmaTuron and @miquelduranfrigola 
[PhakinProError.txt](https://github.com/ersilia-os/eos39dp/files/15467172/PhakinProError.txt)

**Comment by GemmaTuron** [comment]
Hello @sucksido 

As we have discussed previously, when you run into an issue you don't know how to solve, please do not only paste the error but detail what you think might be going on and what have you tried to solve it. IT will make giving feedback much easier for the team. thanks

**Comment by sucksido** [comment]
@GemmaTuron my findings on the error suggest the following:

Run the script manually to see where it fails: bash /tmp/ersilia-ms8c82iv/script.sh

Ensure all dependencies are installed and the environment is correctly set up. Check for any missing packages or version mismatches.

Review the log file /tmp/ersilia-u39204d1/command_outputs.log for detailed error messages.

**Comment by GemmaTuron** [comment]
Hi @sucksido 

sorry I do not understand:
1) Have you done the above steps or you plan on doing them? 
2) Have you manually run the model in your system using the option `--repo_path` and it has worked?

**Comment by GemmaTuron** [comment]
This is the the part where it explains the steps to check model is working before opening the PR:
https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/incorporate-models/example-of-the-model-incorporation-workflow#id-5.-run-the-local-model-inside-ersilia

**Comment by sucksido** [comment]
Still testing locally and making sure I have the right version of all the dependancies and all scenarios are covered

**Comment by GemmaTuron** [comment]
Hello @sucksido 
Please can you detail the steps you are taking so we can guide you? I understood the model was already working locally since you opened the PR, so what is currently failing?

**Comment by sucksido** [comment]
[conda_package_list.txt](https://github.com/user-attachments/files/15887585/conda_package_list.txt)
Hi @GemmaTuron 

Commands used to test locally:

conda activate ersilia

`[log_output.txt](https://github.com/user-attachments/files/15887580/log_output.txt)`

Tried to install the following packages but didn't solve the problem:

numpy: Version 1.22.4 (compatible with pandas and scipy requirements)
scipy: Version 1.9.3
pandas: Version 1.4.3
Cython


Also tried to run this command manually but I get the same output:
`bash /tmp/ersilia-m2yvh9uo/script.sh 2>&1 | tee -a /tmp/ersilia-mquhvun5/command_outputs.log`

I have attached dependencies installed and log file of the error. I need help is this is currently a blocker

**Comment by GemmaTuron** [comment]
Hi @sucksido 

Please, let's take this step by step and answer all the questions:
1. What commands are you using to test the model? Conda activate ersilia is just to activate the ersilia environment and has nothing to do with the model in particular
2. Before making a PR you did assure the model was working. What did you test then? Please explain and ensure you can reproduce it
3. Have you tried the installation from the local repository as I asked? What was the result of this and please do attach the log files

I need better explanations of what commands you are running and what you are getting with each.

**Comment by sucksido** [comment]
[log_output.txt](https://github.com/user-attachments/files/15896793/log_output.txt)

**Comment by sucksido** [comment]
[out19062024.csv](https://github.com/user-attachments/files/15897662/out19062024.csv)
[test.csv](https://github.com/user-attachments/files/15897664/test.csv)

**Comment by sucksido** [comment]
Hi @GemmaTuron 

Have you done the above steps or you plan on doing them? - Yes I have
Have you manually run the model in your system using the option --repo_path and it has worked? - After running this commnad : 
```
conda activate ersilia
ersilia -v fetch eos39dp --repo_path ~/code/eos39dp
```

I am getting the error on the attached log_output.txt


What commands are you using to test the model? Conda activate ersilia is just to activate the ersilia environment and has nothing to do with the model in particular - Yes I am, just forgot to attach this command -  
```

conda activate ersilia
ersilia -v fetch eos39dp --repo_path ~/code/eos39dp
```

Before making a PR you did assure the model was working. What did you test then? Please explain and ensure you can reproduce it - 
conda activate phakinpro-env-py38
`(phakinpro-env-py38) success@success-Dell-G15-5530:~/code/eos39dp/model/framework$ bash run.sh . ~/test.csv ~/out19062024.csv|             `                                                                                                                                                                    


Have you tried the installation from the local repository as I asked? What was the result of this and please do attach the log files - attached the log_output.txt
`- ersilia -v fetch eos39dp --repo_path ~/code/eos39dp`

**Comment by sucksido** [comment]
[phaking_output.txt](https://github.com/user-attachments/files/15897712/phaking_output.txt)

**Comment by GemmaTuron** [comment]
Hi @sucksido 
Thansk for the explanations.
The error clearly points to the cpython package. Why are you installing it? I do not see this as a requirement on the original code. Also please do not use a requirements.txt file on the repository as this can be confused with the actual requirements specified in the dockerfile. 

If it works with run.sh but not when installing from Ersilia there is a package that is not in its right version
Compare the packages in the conda environment created manually and the environment that ersilia creates and let us know if all is the same. Attach both files as well for clarity.

**Comment by GemmaTuron** [comment]
More comments:
- Both the .pgz and .pbz2 files are needed? What is the difference between them?
- Revise the git lfs tracking of objects that are non existing
- The main.py file has functions that are not used, please clean this up
- The parsing of the output is not adapted to the multioutput we are getting. Please revise and make sure you are passing all the results as single columns with the right headers. I am referring to this piece of code:
```
with open(output_file, "w") as f:
    writer = csv.writer(f)
    writer.writerow(["value"])
    for o in outputs:
        writer.writerow([o])
```

that will only write a single output with header "value"

**Comment by GemmaTuron** [comment]
More questions:
I see a few packages that we probably don't need. To make the model slimmer we can modify the code in phakinpro.py once the model is working
What is the `calculate_ad` property that you pass as `False`? and is the write_csv the best function to use or we could use another at a lower level, like `main`?

**Comment by sucksido** [comment]
hi @GemmaTuron 
The error clearly points to the cpython package. Why are you installing it? - **I thought it was a requirement when i tried to google the error, I will uninstall it.**

I do not see this as a requirement on the original code. Also please do not use a requirements.txt file on the repository as this can be confused with the actual requirements specified in the dockerfile.  - **Noted I will specifiy all in the docker file**

If it works with run.sh but not when installing from Ersilia there is a package that is not in its right version
Compare the packages in the conda environment created manually and the environment that ersilia creates and let us know if all is the same. Attach both files as well for clarity. - **Noted , I will compare and attach both files**

**Comment by sucksido** [comment]
Both the .pgz and .pbz2 files are needed? What is the difference between them? - **these are 2 different compression methods. .pgz: Typically involves gzip compression.
.pbz2: Involves bzip2 compression.
Not sure if we need them both as i didnt want to modify the original code too much**

Revise the git lfs tracking of objects that are non existing - **How do i do this?** 

The main.py file has functions that are not used, please clean this up - Noted I will remove the unused code.

The parsing of the output is not adapted to the multioutput we are getting. Please revise and make sure you are passing all the results as single columns with the right headers. I am referring to this piece of code:
```

with open(output_file, "w") as f:
    writer = csv.writer(f)
    writer.writerow(["value"])
    for o in outputs:
        writer.writerow([o])
```

that will only write a single output with header "value" - Cool, will do that

**Comment by sucksido** [comment]
More questions:
I see a few packages that we probably don't need. To make the model slimmer we can modify the code in phakinpro.py once the model is working - **Yes the can be cut down once the model is working**
What is the calculate_ad property that you pass as False? and is the write_csv the best function to use or we could use another at a lower level, like main? - Most of the code i found as is but once the model works I can refactor the code to be as low levels as possible.

I will compare the versions of the packages and test again and upload both files today

**Comment by sucksido** [comment]
@GemmaTuron I have managed to get past the previous error however the pipeline is still failing though locally it's working.

Pipeline error: 
image

Local output: 
image


There's seems to be an issue with this package/module: ModuleNotFoundError: No module named 'scipy'

**Comment by GemmaTuron** [comment]
Hi @sucksido 

Can you upload both conda env lists, the one you manually created and the one ersilia is creating? it should have the same name as the model. This will allow us to see the package differences between them

**Comment by sucksido** [comment]
hi @GemmaTuron ,

Please see attached
[conda list eos39dp.txt](https://github.com/user-attachments/files/15923929/conda.list.eos39dp.txt)
[conda list ersilia.txt](https://github.com/user-attachments/files/15923930/conda.list.ersilia.txt)

**Comment by GemmaTuron** [comment]
Hi @sucksido 
You are pasting the Ersilia environment itself, not the envirnment where you run the model. I mean to compare the conda environment that you manually created to run the model and the environment that ersilia is creating, which is different than the Ersilia environment itself.

Please attach both but also on your end first compare if there are any differences in packages and versions - this will tell you where the issue might be.

**Comment by sucksido** [comment]
@GemmaTuron please see attached
[packages_created_by_ersilia.txt](https://github.com/user-attachments/files/15926578/packages_created_by_ersilia.txt)

**Comment by GemmaTuron** [comment]
Hi @sucksido 
I think there is some confusion, let's see if I can clarify. You have a conda environment that you created manually (probably named phakinpro or something the likes). This environment has all the requirements the model needs to run, because it did work using the run.sh command right? that is the first conda environment that you need to get the dependencies from (and python version!)
Then ersilia is creating a conda environment named eos39dp - this will have some dependency clash that leads to the issue you are facing of scipy not being recognised. 

You need to compare the phakinpro and the eos39dp conda environments and see if you have any dependencies that are different, or different versions - let me know what do you find out here.

**Comment by sucksido** [comment]
I think I understand that better @GemmaTuron 

Here are the 2 files we need to compare.

I see scipy                     1.10.1 is missing from the eos39pd file.
[conda_phakinpro-env-py38.txt](https://github.com/user-attachments/files/15927945/conda_phakinpro-env-py38.txt)
[conda list eos39dp.txt](https://github.com/user-attachments/files/15927948/conda.list.eos39dp.txt)

**Comment by GemmaTuron** [comment]
ok, to be sure, the dockerfile you have in your local repo is [this one](https://github.com/sucksido/eos39dp/blob/main/Dockerfile)?
I see that you have commented out scipy, so it is not getting installed, which is the source of the scipy not found error.
I cannot see either scikit-learn requirement? why is it not there? The requirements are listed in the source code repository for PhaKinPro. All those packages should be installed for sure.

I also see another important one: you are using py38 in phakinpro but the dockerfile is specifying py310 in the top: F`ROM bentoml/model-server:0.11.0-py310`
Also, cython is not speficied in the original model requirements, so I certainly would not specify it, as mentioned before.

I suggest:
- Modify the Dockerfile so it uses Py38
- Add all the necessary requirements and eliminate the non-necessary ones
- Do not specify any version in the Dockerfile for any package and see if pip is able to resolve itself
- Try fetching the model locally with this modified Dockerfile, and if it works, you simply need to look for the specific versions in the conda environment created and pin them

**Comment by sucksido** [comment]
I see that you have commented out scipy, so it is not getting installed, which is the source of the scipy not found error.
I cannot see either scikit-learn requirement? why is it not there? The requirements are listed in the source code repository for PhaKinPro. All those packages should be installed for sure. - I commented it out because it wasnt making any different whether it's there or not

I also see another important one: you are using py38 in phakinpro but the dockerfile is specifying py310 in the top: FROM bentoml/model-server:0.11.0-py310
Also, cython is not speficied in the original model requirements, so I certainly would not specify it, as mentioned before. - oK I can remove it and test again

I suggest:

Modify the Dockerfile so it uses Py38 - Cool
Add all the necessary requirements and eliminate the non-necessary ones  - Noted
Do not specify any version in the Dockerfile for any package and see if pip is able to resolve itself - Noted
Try fetching the model locally with this modified Dockerfile, and if it works, you simply need to look for the specific versions in the conda environment created and pin them - I will test again using this approach. Thank you

**Comment by GemmaTuron** [comment]
I will merge this PR to get the code in the main branch and work from there

**Pull request merged**
